### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by l11x0m7** [eyalbd2/Semantically-Driven-Sentence-Fusion#1]
Hi, 
As the paper is published in EMNLP, I wonder when the code can be released?

Thanks

**Comment by eyalbd2** [comment]
Hi,
It will be released in a couple of days.

Eyal

בתאריך יום ג׳, 13 באוק׳ 2020, 15:14, מאת lxm ‏<notifications@github.com>:

**Comment by eyalbd2** [comment]
The code, the data, and models have been uploaded.

**Comment by l11x0m7** [comment]
Nice! Thank you!
